config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    resources :comments
  end
  resources :users,only: [:new,:create]
  get 'login'     ,to: 'sessions#new'
  post 'login'    ,to: 'sessions#create'
  delete 'logout' ,to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :response , presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :description , presence: true,length: {minimum: 10,maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
   before_save {self.email = email.downcase}
   has_many :posts
   validates :name , presence: true,
                         uniqueness: { case_sensitive: false },
                         length: {minimum: 3,maximum: 25}
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email , presence: true,
                      uniqueness: { case_sensitive: false },
                      length: {maximum: 105},format: {with: VALID_EMAIL_REGEX}
   has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_user

  helper_method :current_user,:logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    ! !current_user
  end
  def require_user
    if !logged_in?
      flash[:notice] = "Yoy have to logged in to do these actions"
      redirect_to login_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController



  def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
     redirect_to post_path(@post)
  end
  private
  def comment_params
   params.require(:comment).permit(:response)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 skip_before_action :require_user , except: [:new,:create,:update]
 before_action :set_post,only: [:edit,:update,:destroy,:show]

   def index
     @posts = Post.all
   end

   def new
     @post = Post.new
   end

   def create
     @post = Post.new(post_params)
     @post.user = current_user
     if @post.save
       flash[:notice] = "Post was created successfully"
       redirect_to posts_path
     else
       flash[:alert] = "Something went wrong try again"
       render 'new'
     end
   end

   def show
   end

   def edit
   end

   def update
     @post.update(post_params)
     if @post.update(post_params)
       flash[:notice] = "post was updated successfully"
       redirect_to posts_path
     else
       render 'edit'
     end
   end

   def destroy
     @post.destroy
     flash[:notice] = "Post was deleted"
     redirect_to posts_path
   end

   private

   def set_post
      @post = Post.find(params[:id])
   end

   def post_params
     params.require(:post).permit(:description)
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 skip_before_action :require_user, only: [:new,:create]
 
  def new
  end

   def create
     user = User.find_by(email: params[:session][:email].downcase)
     if user && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       flash[:notice] = "Logged in Successfully"
       redirect_to new_post_path
     else
       flash.now[:alert] = "There was something wrong with your login details"
       render 'new'
     end
   end
   def destroy
     session[:user_id] = nil
     flash[:notice] = "Logged Out"
     redirect_to root_path
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_user, only: [:new,:create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.name} you are signed up"
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_comment.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 ">
  <div class="card text-center shadow mb-5 bg-white rounded">
    <div class="card-body font-italic">
      <h5 class="card-title">Comments</h5>
        <% @post.comments.each do |comment| %>
            <p class="card-text text-left">
              <%= comment.response %> <small>( Created  <%= time_ago_in_words(comment.created_at)  %> ago , Updated <%= time_ago_in_words(comment.updated_at)  %>   ago)</small></p>
            <hr>
        <% end %>
    </div>
  </div>
 </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build],class: "shadow p-3 mb-5 bg-info rounded",local: true) do |f| %>
<div class="form-group row">
  <%= f.label :response ,"Comment" , class: "col-2 col-form-label text-dark"%>
  <div class="col-10">
    <div class="row">
      <div class="col-10">
        <%= f.text_field :response ,rows: 10 ,class: "form-control shadow rounded" ,placeholder: "Comment here"%>
       </div>
       <div class="col-2">
        <%= f.button :submit ,class: "btn btn-info" %>
       </div>
     </div>
  </div>
</div>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name,msg| %>
       <% if name == "notice" %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
         <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <% else %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= msg %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "OraxTech Assignment",root_path,class:"navbar-brand"  %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to "Create Post",new_post_path,class: "nav-link" %>
      </li>
    <% end %>
  </ul>
  <ul class="navbar-nav ml-auto">
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Logout",logout_path,class: "nav-link",method: :delete %>
      </li>
    <% else %>
      <li class="nav-item">
         <%= link_to "Login",login_path,class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up",new_user_path,class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row justify-content-center mt-4">
  <div class="col-10">
    <%= render 'shared/errors', obj: @post %>
    <%= form_with(model: @post ,class: "shadow p-3 mb-5 bg-info rounded",local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :description , class: "col-2 col-form-label text-light"%>
        <div class="col-10">
        <%= f.text_area :description ,rows: 10 ,class: "form-control shadow rounded" ,placeholder: "Enter the description of post"%>
        </div>
      </div>
      <div class="form-group row justify-content-center">
       <%= f.submit class:"btn btn-outline-light btn-lg" %>
      </div>
    <% end %>
  </div>
  <%= link_to '[Cancel and Back to Posts Listing]',root_path ,class: "text-info"%>
</div>

app/views/posts/edit.html.erb
<div class="container">

   <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 ">
      <% @posts.each do |post| %>
        <div class="card text-center mt-4 shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
             <% if post.user %>
              by <i class="fa fa-user"></i> <%= post.user.name  %>
             <% end %>
          </div>
          <div class="card-body">
            <p class="card-text"><%= truncate(post.description, length: 100) %></p>
            <%= link_to 'View',post_path(post), class: "btn btn-outline-success"%>
            <% if logged_in? && post.user==current_user %>
              <%= link_to 'Edit',edit_post_path(post), class: "btn btn-outline-info"%>
              <%= link_to 'Delete',post_path(post),method: :delete ,class: "btn btn-outline-danger", data: {confirm: "Are You Sure?"}%>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created  <%= time_ago_in_words(post.created_at)  %> ago , Updated <%= time_ago_in_words(post.updated_at)  %>   ago</small>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">

   <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
   <div class="row justify-content-md-center">
     <div class="col-8 ">
         <div class="card text-center mt-4 shadow mb-5 bg-white rounded">
           <div class="card-header font-italic">
              <% if @post.user %>
               by <i class="fa fa-user"></i> <%= @post.user.name  %>
              <% end %>
           </div>
           <div class="card-body">
             <div class="card-text text-left"><%= simple_format(@post.description) %></div>
              <% if logged_in? && @post.user == current_user %>
               <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-outline-info"%>
               <%= link_to 'Delete', post_path(@post),method: :delete ,class: "btn btn-outline-danger", data: {confirm: "Are You Sure?"}%>
              <% end %>
            </div>
           <div class="card-footer text-muted">
             <small>Created  <%= time_ago_in_words(@post.created_at)  %> ago , Updated <%= time_ago_in_words(@post.updated_at)  %>   ago</small>
           </div>
         </div>
     </div>
   </div>
   <% if @post.comments.any? %>
      <%= render 'comments/comment' %>
   <% end %>

   <% if logged_in? %>
     <div class="row justify-content-md-center">
       <div class="col-8 ">
       <div class="card text-center shadow mb-5 bg-white rounded">
         <div class="card-body font-italic">
            <%= render 'comments/form' %>
         </div>
       </div>
      </div>
     </div>
   <% end %>
 </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
   <h2 class="alert-heading">These errors prevent the to save</h2>
  <% obj.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container">

  <div class="row justify-content-center mt-4 ">
    <div class="col-10">
      <%= render 'shared/errors',obj: @user %>
      <%= form_with(model: @user ,class: "shadow p-3 mb-5 bg-info rounded",local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name , class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.text_field :name , class: "form-control shadow rounded" ,placeholder: "Enter a username"%>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email , class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.email_field :email  ,class: "form-control shadow rounded" ,placeholder: "Enter your email"%>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :password , class: "col-2 col-form-label text-light"%>
          <div class="col-10">
            <%= f.password_field :password  ,class: "form-control shadow rounded" ,placeholder: "Enter Password"%>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit "Sign Up", class:"btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
       <%= link_to '[Cancel and Back to Posts Listing]',root_path ,class: "text-info ml-6"%>
  </div>
</div>